name = "aoc"
defaultTargets = ["aoc"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "Aoc"

[[lean_exe]]
name = "aoc"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.14.0"

[[require]]
name = "Parser"
scope = "fgdorais"
rev = "711662ab6f3c4c0080f6379737b41b1089d3d3f8"
