name = "aoc"
defaultTargets = ["aoc"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "Aoc"

[[lean_exe]]
name = "aoc"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.13.0"

[[require]]
name = "Parser"
scope = "fgdorais"
rev = "4d74c484a91420b5866f9d883d597bfae4232de8"
